# Generated by Django 5.2.3 on 2025-07-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='company',
            field=models.CharField(max_length=200),
        ),
    ]
