# Generated by Django 5.2.4 on 2025-07-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactapp', '0002_alter_enquiry_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcriberUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
