# Generated by Django 5.2.4 on 2025-07-26 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactapp', '0003_subcriberuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubcriberUser',
            new_name='SubscriberUser',
        ),
    ]
